version: "3.7"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: app
    container_name: app_container
    restart: unless-stopped
    ports:
     - 3001:3001
    volumes:
      - ./app:/home/app
    networks:
      - prom_network


  prom:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    image: prometheus
    container_name: prom_container
    restart: unless-stopped
    volumes:
      - prometheus-storage:/prometheus
    ports:
      - 9090:9090
    links:
      - app
    networks:
      - prom_network

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - prom_network

  grafana: 
    image: grafana/grafana
    container_name: grafana_container
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    links:
      - prom
    networks:
      - prom_network
   

volumes:
  grafana-storage: {}
  prometheus-storage: {}


networks:
  prom_network:
    driver: bridge
